version: 2

sources:
  - name: elook_commerce
    database: ELOOK_COMMERCE
    schema: RAW
    tables:

      - name: orders
        columns:
          - name: order_id
            tests:
              - not_null
              - unique
          - name: user_id
            tests:
              - not_null
              - relationships:
                  to: source('elook_commerce', 'users')
                  field: id

      - name: users
        columns:
          - name: id
            tests:
              - not_null
              - unique

      - name: products
        columns:
          - name: id
            tests:
              - not_null
              - unique

      - name: order_items
        columns:
          - name: product_id
            tests:
              - relationships:
                  to: source('elook_commerce', 'products')
                  field: id
