version: 2

sources:
  - name: elook_commerce
    database: ELOOK_COMMERCE
    schema: RAW
    tables:

      - name: orders
        description: "Contains order-level details"
        columns:
          - name: order_id
            tests:
              - not_null
              - unique
          - name: user_id
            tests:
              - not_null
          - name: status
            tests:
              - accepted_values:
                  values: ['Returned','Processing','Complete','Shipped','Cancelled']

      - name: order_items
        description: "Contains ordered items in each order"
        columns:
          - name: user_id
            tests:
              - not_null
          - name: order_id
            tests:
              - not_null
          - name: product_id
            tests:
              - not_null
          - name: sale_price
            tests:
              - not_null

      - name: users
        description: "Contains user information"
        columns:
          - name: id
            tests:
              - not_null
              - unique
          - name: email
            tests:
              - not_null

      - name: products
        description: "Contains product catalog details"
        columns:
          - name: id
            tests:
              - not_null
          - name: category
            tests:
              - not_null
